# Generated by Django 4.2 on 2026-06-24 05:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('authors', models.CharField(blank=True, max_length=300, verbose_name='Mualliflar')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='Yil')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Nashriyot')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL manzil')),
                ('category', models.CharField(choices=[('book', 'Kitob'), ('article', 'Maqola'), ('website', 'Veb-sayt'), ('video', 'Video'), ('other', 'Boshqa')], default='book', max_length=20, verbose_name='Tur')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Adabiyot',
                'verbose_name_plural': 'Foydalanilgan adabiyotlar',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PracticalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Topshiriq nomi')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Topshiriq mazmuni')),
                ('task_file', models.FileField(blank=True, null=True, upload_to='assignments/tasks/', verbose_name='Topshiriq fayli (PDF/Word/ZIP)')),
                ('deadline_days', models.IntegerField(default=7, verbose_name='Muddat (kunlar)')),
                ('max_score', models.IntegerField(default=100, verbose_name='Maksimal ball')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='courses.lesson', verbose_name='Dars')),
            ],
            options={
                'verbose_name': 'Amaliy topshiriq',
                'verbose_name_plural': 'Amaliy topshiriqlar',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='assignments/submissions/', verbose_name='Bajarilgan ish fayli')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('submitted', 'Yuborildi'), ('reviewed', "Ko'rib chiqildi"), ('accepted', 'Qabul qilindi'), ('rejected', 'Qaytarildi')], default='submitted', max_length=20, verbose_name='Holat')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Ball')),
                ('feedback', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.practicalassignment', verbose_name='Topshiriq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuborilgan ish',
                'verbose_name_plural': 'Yuborilgan ishlar',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'user')},
            },
        ),
    ]
