# Generated by Django 4.2 on 2026-06-24 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_reference_practicalassignment_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('pass_score', models.IntegerField(default=60, verbose_name="O'tish balli (%)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chiqish testi',
                'verbose_name_plural': 'Chiqish testlari',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='practicalassignment',
            name='canva_url',
            field=models.URLField(blank=True, null=True, verbose_name='Canva havolasi (ixtiyoriy)'),
        ),
        migrations.CreateModel(
            name='FinalTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Ball (%)')),
                ('correct', models.IntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total', models.IntegerField(default=0, verbose_name='Jami savollar')),
                ('passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.finaltest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.finaltest')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FinalTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.finaltestquestion')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
            },
        ),
    ]
