# Generated by Django 4.2 on 2026-06-25 07:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_finaltest_practicalassignment_canva_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Muallif', max_length=200, verbose_name="To'liq ism")),
                ('position', models.CharField(default="Raqamli va Axborot Texnologiyalari sohasidagi o'qituvchi", max_length=300, verbose_name='Lavozim/Mutaxassislik')),
                ('bio_short', models.TextField(default='Raqamli media kompetentligi sohasida tajribali pedagog va tadqiqotchi.', verbose_name='Qisqa tarjimai hol (hero)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Rasm')),
                ('experience_years', models.CharField(default='10+', max_length=20, verbose_name='Tajriba yillari')),
                ('students_count', models.CharField(default='500+', max_length=20, verbose_name="O'quvchilar")),
                ('publications_count', models.CharField(default='20+', max_length=20, verbose_name='Nashrlar')),
                ('courses_count', models.CharField(default='15+', max_length=20, verbose_name='Kurslar')),
                ('education_text', ckeditor.fields.RichTextField(blank=True, verbose_name="Ta'lim")),
                ('career_text', ckeditor.fields.RichTextField(blank=True, verbose_name='Kasbiy faoliyat')),
                ('science_text', ckeditor.fields.RichTextField(blank=True, verbose_name='Ilmiy faoliyat')),
                ('online_text', ckeditor.fields.RichTextField(blank=True, verbose_name='Onlayn faoliyat')),
                ('skill1_name', models.CharField(default='Raqamli media savodxonligi', max_length=100, verbose_name="1-ko'nikma")),
                ('skill1_percent', models.IntegerField(default=95, verbose_name="1-ko'nikma %")),
                ('skill2_name', models.CharField(default='Axborot texnologiyalari', max_length=100, verbose_name="2-ko'nikma")),
                ('skill2_percent', models.IntegerField(default=90, verbose_name="2-ko'nikma %")),
                ('skill3_name', models.CharField(default='Pedagogika va metodika', max_length=100, verbose_name="3-ko'nikma")),
                ('skill3_percent', models.IntegerField(default=92, verbose_name="3-ko'nikma %")),
                ('skill4_name', models.CharField(default='Kiberhavfsizlik', max_length=100, verbose_name="4-ko'nikma")),
                ('skill4_percent', models.IntegerField(default=80, verbose_name="4-ko'nikma %")),
                ('email', models.EmailField(blank=True, default='info@mediacomp.uz', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='+998 97 911 44 59', max_length=30, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, default="Samarqand, O'zbekiston", max_length=200, verbose_name='Manzil')),
                ('research_topics', models.TextField(default="Media savodxonligi\nRaqamli kompetentlik\nAxborot xavfsizligi\nOnlayn ta'lim texnologiyalari\nKiberhavfsizlik asoslari\nFake news va dezinformatsiya", verbose_name="Tadqiqot yo'nalishlari (har birini yangi qatorga yozing)")),
            ],
            options={
                'verbose_name': 'Muallif haqida (sahifa)',
                'verbose_name_plural': 'Muallif haqida (sahifa)',
            },
        ),
    ]
